
//   ╔═════╦═════╗   ╔───╦═══════╗   ╔═══════╗   ╔═══════╦───════╦════───╦═══════╗   ╔═══════╗   ╔═══════╗   ╔═══════╗   ╔═══════╗
//   ║     ║     ║   ║   ║       ║   ║       ║   ║       ║       ║       ║       ║   ║       ║   ║       ║   ║       │   ║       ║
//   ║     ║     ║   ║   ║       │   ║       ║   ║       ║       ║       ║       ║   ║     ╔═╝   ║     ╔═╝   ║       │   ║       ║
//   ║     ║     ║   ║   ║       │   ╠═══╦═══╝   ║       ║       ║       ╠═══════╣   ╠═════╣     ╠═════╣     ╠═══════╣   ╠═══╦═══╝
//   ║     ║     ║   ║   ║       │   ║   ║       ║       ║       ║       ║       ║   ║     ╚═╗   ║     ╚═╗   ║       │   ║   ║
//   ║     ║     ║   ║   ║       ║   ║   ║       ║       ║       ║       ║       ║   ║       ║   ║       ║   ║       │   ║   ║
// ──╩─────╩─────╩───╝   ╚═══════╩───╝   ╚════───╩═══════╩───────╩───────╝       ╚───╩═══════╩───╩═══════╩───╩═══════╩───╝   ╚════── MICROTABBER

set window-x 0;
set window-y 0;
set window-x-offset 0;
set window-y-offset 0;
set window-horizontal-alignment center;
set window-vertical-alignment center;
set window-width "3 * 320 + 3 * 2 * 20 + 4 * 20" integer;
set window-height "3 * 20 + 3 * 180 + 3 * 2 * 20 + 4 * 20" integer;

set selection-margin 20;
set selection-padding 20;
set selection-gap 0;

set client-x 0;
set client-y 0;
set client-x-offset 0;
set client-y-offset 0;
set client-horizontal-alignment center;
set client-vertical-alignment center;
set client-width 320 integer;
set client-height 180 integer;

set title-x 0;
set title-y 0;
set title-x-offset 0;
set title-y-offset 0;
set title-horizontal-alignment center;
set title-vertical-alignment center;
set title-width 320 integer;
set title-height 20 integer;

set which-monitor pointer;
set client-order creation;
set allow-circular-navigation true;
set font "-misc-fixed-medium-r-semicondensed--13-*-*-*-*-*-iso10646-1";

set window-background 0xFF171717;
set selection-background 0xFF171717;
set client-background 0xFF9A9996;
set title-foreground 0xFF000000;
set title-background 0xFFFFFFFF;

set selected-selection-background 0xFF1793D0;
set selected-client-background 0xFF9A9996;
set selected-title-foreground 0xFF000000;
set selected-title-background 0xFFFFFFFF;

set title-position above-client;
set title-text-cutoff 50;
set title-text-horizontal-alignment center;
set title-text-vertical-alignment center;
set selected-client focused;
set selection-axis horizontal;
set selection-fit-amount 3;
set selection-action move-to-desktop;
set window-circle-radius 12;

grab-keycode mod-4  23 show;
grab-keycode mod-4  58 restart;
grab-keycode mod-4 113 select-left;
grab-keycode mod-4 114 select-right;
grab-keycode mod-4 111 select-above;
grab-keycode mod-4 116 select-below;
