
//   ╔═════╦═════╗   ╔───╦═══════╗   ╔═══════╗   ╔═══════╦───════╦════───╦═══════╗   ╔═══════╗   ╔═══════╗   ╔═══════╗   ╔═══════╗
//   ║     ║     ║   ║   ║       ║   ║       ║   ║       ║       ║       ║       ║   ║       ║   ║       ║   ║       │   ║       ║
//   ║     ║     ║   ║   ║       │   ║       ║   ║       ║       ║       ║       ║   ║     ╔═╝   ║     ╔═╝   ║       │   ║       ║
//   ║     ║     ║   ║   ║       │   ╠═══╦═══╝   ║       ║       ║       ╠═══════╣   ╠═════╣     ╠═════╣     ║═══════╣   ╠═══╦═══╝
//   ║     ║     ║   ║   ║       │   ║   ║       ║       ║       ║       ║       ║   ║     ╚═╗   ║     ╚═╗   ║       │   ║   ║
//   ║     ║     ║   ║   ║       ║   ║   ║       ║       ║       ║       ║       ║   ║       ║   ║       ║   ║       │   ║   ║
// ──╩─────╩─────╩───╝   ╚═══════╩───╝   ╚════───╩═══════╩───────╩───────╝       ╚───╩═══════╩───╩═══════╩───╩═══════╩───╝   ╚════── MICROTABBER

set window-x 0;
set window-y 0;
set window-x-offset 0;
set window-y-offset 0;
set window-horizontal-alignment center;
set window-vertical-alignment center;
set window-width 80 percentage;
set window-height 80 percentage;

set selection-margin 20;
set selection-padding 20;
set selection-gap 10;

set client-x 0;
set client-y 0;
set client-x-offset 0;
set client-y-offset 0;
set client-horizontal-alignment center;
set client-vertical-alignment center;
set client-width 320 integer;
set client-height 180 integer;

set title-x 0;
set title-y 0;
set title-x-offset 0;
set title-y-offset 0;
set title-horizontal-alignment center;
set title-vertical-alignment center;
set title-width 320 integer;
set title-height 20 integer;

set which-monitor pointer;
set client-order creation;
set allow-circular-navigation true;
set font "-misc-fixed-medium-r-semicondensed--13-*-*-*-*-*-iso10646-1";

set window-background 0xFF171717;
set selection-background 0xFF7F7F7F;
set selected-selection-background 0xFFFF0000;
set client-background 0xFF2D3D59;
set title-foreground 0xFF000000;
set title-background 0xFF2D3D59;

set title-text-cutoff 50;

grab-keycode mod-4  23 show;
grab-keycode mod-4 113 select-previous;
grab-keycode mod-4 114 select-next;
grab-keycode mod-4 111 select-above;
grab-keycode mod-4 116 select-below;
