//   ╔═════╦═════╗   ╔───╦═══════╗   ╔═══════╗   ╔═══════╦───════╦════───╦═══════╗   ╔═══════╗   ╔═══════╗   ╔═══════╗   ╔═══════╗
//   ║     ║     ║   ║   ║       ║   ║       ║   ║       ║       ║       ║       ║   ║       ║   ║       ║   ║       │   ║       ║
//   ║     ║     ║   ║   ║       │   ║       ║   ║       ║       ║       ║       ║   ║     ╔═╝   ║     ╔═╝   ║       │   ║       ║
//   ║     ║     ║   ║   ║       │   ╠═══╦═══╝   ║       ║       ║       ╠═══════╣   ╠═════╣     ╠═════╣     ║═══════╣   ╠═══╦═══╝
//   ║     ║     ║   ║   ║       │   ║   ║       ║       ║       ║       ║       ║   ║     ╚═╗   ║     ╚═╗   ║       │   ║   ║
//   ║     ║     ║   ║   ║       ║   ║   ║       ║       ║       ║       ║       ║   ║       ║   ║       ║   ║       │   ║   ║
// ──╩─────╩─────╩───╝   ╚═══════╩───╝   ╚════───╩═══════╩───────╩───────╝       ╚───╩═══════╩───╩═══════╩───╩═══════╩───╝   ╚════── MICROTABBER

set x 0;
set y 0;
set x-offset 0;
set y-offset 0;
set horizontal-alignment center;
set vertical-alignment center;
set width integer;
set height integer;
set which-monitor pointer;

set client-order creation;
set allow-circular-navigation true;

grab-keycode mod-4  23 show;
grab-keycode mod-4 113 select-previous;
grab-keycode mod-4 114 select-next;
grab-keycode mod-4 111 select-above;
grab-keycode mod-4 116 select-below;
